# We want to extend the system.site configuration
system.site:
  mapping:
    # Our field name is 'siteapikey'
    siteapikey:
      type: label
      label: 'Site API Keys'
dependencies:
  module:
    - site_api_key
  enforced:
    module:
      - site_api_key